-- ============================================================================
-- Radio Playlist Dashboard — Supabase / Postgres schema
-- ============================================================================
-- Mirrors the live SQLite schema in scripts/db.py, with three deliberate
-- differences, each called out at its column:
--
--   1. stations.website      — exists in the live SQLite DB and in
--                              STATIONS_CONFIG, but scripts/db.py's CREATE TABLE
--                              never declared it and _seed_stations() never
--                              inserts it. Declared explicitly here so a rebuild
--                              cannot silently lose it.
--   2. tracks.station_slug   — denormalized. Every generated JSON row already
--                              carries it, and the frontend filters on it, so
--                              storing it avoids a join on every public read.
--   3. tracks.song_image     — NOT POPULATED BY ANYTHING TODAY. There is no
--                              cover-art field anywhere in the pipeline;
--                              shazamio_proxy.py would have to be changed to
--                              emit one. Nullable placeholder, reserved.
--
-- Apply with: Supabase dashboard -> SQL Editor -> paste -> Run.
-- Safe to re-run: every statement is idempotent.
-- ============================================================================


-- ── stations ────────────────────────────────────────────────────────────────
-- 8 rows. Ids are preserved from SQLite (1-8) so tracks.station_id FKs survive
-- the backfill unchanged.
create table if not exists public.stations (
    id          bigint generated by default as identity primary key,
    slug        text    not null unique,
    name        text    not null,
    stream_url  text    not null,
    proxy_port  integer not null unique,
    color       text    default '#6ae3c1',
    enabled     boolean default true,
    website     text    default '',          -- see note 1 above
    created_at  timestamptz default now()
);


-- ── tracks ──────────────────────────────────────────────────────────────────
-- One row per recognized play. ~1 insert / 90s across all 8 stations.
create table if not exists public.tracks (
    id            bigint generated by default as identity primary key,
    station_id    bigint  references public.stations(id) on delete cascade,
    station_slug  text    not null,          -- see note 2 above
    artist        text    not null,
    title         text    not null,
    text          text,
    url           text,
    shazam_key    text,
    isrc          text,                      -- NULL on all pre-epoch rows (387 of
                                             -- them) and NOT backfillable without
                                             -- re-recognition. See AGENTS.md.
    song_image    text,                      -- see note 3 above
    recognized_at timestamptz not null,
    created_at    timestamptz default now()
);

create index if not exists idx_tracks_recognized_at   on public.tracks (recognized_at desc);
create index if not exists idx_tracks_station_id      on public.tracks (station_id);
create index if not exists idx_tracks_station_recog   on public.tracks (station_id, recognized_at desc);
create index if not exists idx_tracks_station_slug    on public.tracks (station_slug);
create index if not exists idx_tracks_shazam_key      on public.tracks (shazam_key);
create index if not exists idx_tracks_artist_title    on public.tracks (artist, title);
create index if not exists idx_tracks_isrc            on public.tracks (isrc);

-- Dedupe / upsert key. Verified unique across all 1,891 live rows, and no row
-- has an empty shazam_key, so this is safe as a natural key. It is what lets
-- both the backfill and the daemon use ON CONFLICT DO NOTHING and stay
-- idempotent — re-running the backfill after a Supabase outage reconciles the
-- gap instead of duplicating history.
create unique index if not exists uq_tracks_natural_key
    on public.tracks (station_id, shazam_key, recognized_at);


-- ── non_music_log ───────────────────────────────────────────────────────────
-- Silence / talk / ad intervals. Copied as-is.
--
-- KNOWN BAD DATA, carried over deliberately: until the 2026-08 fix, updater.py
-- closed the open interval instead of extending it on continuous silence, so
-- this table has ~5,244 rows against 1,891 tracks and its total durations
-- understate reality. AGENTS.md assigns this table to a separate agent, so the
-- migration copies it verbatim and does NOT attempt a repair. The bug was fixed
-- in scripts/updater.py: a no-track poll now only starts an interval when none
-- is open, so continuous silence extends one interval instead of flip-flopping.
create table if not exists public.non_music_log (
    id          bigint generated by default as identity primary key,
    station_id  bigint references public.stations(id) on delete cascade,
    started_at  timestamptz not null,
    ended_at    timestamptz,                 -- NULL = still open (2 such rows today)
    reason      text default 'unknown'
);

create index if not exists idx_non_music_station on public.non_music_log (station_id);
create index if not exists idx_non_music_started on public.non_music_log (started_at desc);


-- ============================================================================
-- Row Level Security
-- ============================================================================
-- Model: the public may READ everything and WRITE nothing.
--
-- The collector daemon authenticates with the service_role key, which BYPASSES
-- RLS entirely. So granting no write policy at all is what restricts writes to
-- the daemon — there is deliberately no INSERT/UPDATE/DELETE policy below.
-- Adding one would be the bug.
-- ============================================================================

alter table public.stations      enable row level security;
alter table public.tracks        enable row level security;
alter table public.non_music_log enable row level security;

-- Public read.
drop policy if exists "public read stations" on public.stations;
create policy "public read stations"
    on public.stations for select
    to anon, authenticated
    using (true);

drop policy if exists "public read tracks" on public.tracks;
create policy "public read tracks"
    on public.tracks for select
    to anon, authenticated
    using (true);

drop policy if exists "public read non_music_log" on public.non_music_log;
create policy "public read non_music_log"
    on public.non_music_log for select
    to anon, authenticated
    using (true);

-- Belt and braces. RLS already blocks these (no policy grants them), but
-- revoking the table privilege too means a future accidental "allow all"
-- policy still cannot let the public write.
revoke insert, update, delete on public.stations      from anon, authenticated;
revoke insert, update, delete on public.tracks        from anon, authenticated;
revoke insert, update, delete on public.non_music_log from anon, authenticated;


-- ============================================================================
-- Sequence reset (needed by the one-time backfill)
-- ============================================================================
-- migrate_to_supabase.py inserts rows with their original SQLite ids, so that
-- tracks.station_id keeps pointing at the right station. Inserting an explicit
-- id into an identity column does NOT advance the underlying sequence, so
-- without this the daemon's next insert would try id=1 and collide.
--
-- Call once after the backfill:  select public.reset_identity_sequences();
create or replace function public.reset_identity_sequences()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
    perform setval(pg_get_serial_sequence('public.stations', 'id'),
                   coalesce((select max(id) from public.stations), 1), true);
    perform setval(pg_get_serial_sequence('public.tracks', 'id'),
                   coalesce((select max(id) from public.tracks), 1), true);
    perform setval(pg_get_serial_sequence('public.non_music_log', 'id'),
                   coalesce((select max(id) from public.non_music_log), 1), true);
end;
$$;

-- Only the daemon (service_role) may call it; it is a maintenance operation.
revoke execute on function public.reset_identity_sequences() from anon, authenticated;


-- ============================================================================
-- Storage — the aggregate JSON the dashboard actually reads
-- ============================================================================
-- generate_data.py's precomputed aggregates (heatmap matrices, the MDS cluster
-- embedding, the windowed leaderboards) cannot be expressed as a query against
-- the tracks table, so they are published as files instead, at the exact same
-- paths they had under docs/data/.
--
-- DO NOT create the bucket from this file. On current Supabase projects
-- `storage.objects` is owned by `supabase_storage_admin`, so a CREATE POLICY on
-- it from the SQL Editor fails with a permissions error. Create it through the
-- API instead, which the secret key is allowed to do:
--
--     python -c "import sys; sys.path.insert(0,'scripts'); \
--       from supabase_client import get_client; \
--       get_client().storage.create_bucket('dashboard', options={'public': True})"
--
-- A PUBLIC bucket needs no read policy at all — that is the point: reads require
-- no apikey, so the frontend embeds no key whatsoever. Uploads go through the
-- secret key, which bypasses storage RLS.
