#!/usr/bin/env python3
"""
Create analytics table in Supabase for tracking page views and user behavior.

This script:
1. Creates the analytics_events table
2. Sets up RLS policies to allow anonymous INSERT (for public tracking)
3. Creates indexes for efficient querying

Run once: python scripts/create_analytics_table.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from supabase_client import get_client

def create_analytics_schema():
    """Create analytics table and policies in Supabase."""
    
    client = get_client()
    
    # SQL to create the analytics table
    sql = """
    -- Analytics table for tracking page views and user behavior
    CREATE TABLE IF NOT EXISTS public.analytics_events (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id      TEXT NOT NULL,              -- Unique session identifier
        event_type      TEXT NOT NULL,              -- 'page_view', 'tab_click', 'session_end', etc.
        event_data      JSONB,                      -- Flexible data for different event types
        user_agent      TEXT,                       -- Browser/device info
        referrer        TEXT,                       -- Where they came from
        country         TEXT,                       -- Country code (if available)
        city            TEXT,                       -- City (if available)
        ip_hash         TEXT,                       -- Hashed IP for deduplication (not raw IP)
        screen_width    INTEGER,                    -- Screen resolution
        screen_height   INTEGER,
        language        TEXT,                       -- Browser language
        created_at      TIMESTAMPTZ DEFAULT NOW()
    );

    -- Indexes for efficient querying
    CREATE INDEX IF NOT EXISTS idx_analytics_session_id ON public.analytics_events (session_id);
    CREATE INDEX IF NOT EXISTS idx_analytics_event_type ON public.analytics_events (event_type);
    CREATE INDEX IF NOT EXISTS idx_analytics_created_at ON public.analytics_events (created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_analytics_country ON public.analytics_events (country);

    -- Enable RLS
    ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

    -- Allow anonymous INSERT (so the public website can track)
    DROP POLICY IF EXISTS "allow anonymous insert" ON public.analytics_events;
    CREATE POLICY "allow anonymous insert"
        ON public.analytics_events FOR INSERT
        TO anon, authenticated
        WITH CHECK (true);

    -- Allow public SELECT (so the dashboard can read analytics)
    DROP POLICY IF EXISTS "allow public select" ON public.analytics_events;
    CREATE POLICY "allow public select"
        ON public.analytics_events FOR SELECT
        TO anon, authenticated
        USING (true);

    -- Block DELETE/UPDATE from public (only service_role can modify)
    REVOKE UPDATE, DELETE ON public.analytics_events FROM anon, authenticated;
    """
    
    try:
        # Execute the SQL
        result = client.rpc('exec_sql', {'sql': sql}).execute()
        print("✅ Analytics table created successfully")
        return True
    except Exception as e:
        # If rpc doesn't exist, we need to use the Supabase dashboard or a different approach
        print(f"⚠️  Could not execute SQL directly: {e}")
        print("\n📋 Manual setup required:")
        print("1. Go to https://supabase.com/dashboard/project/ktewdeaegtukbosrgxmw/sql")
        print("2. Paste the following SQL and run it:")
        print("\n" + "="*80)
        print(sql)
        print("="*80)
        return False

if __name__ == "__main__":
    print("Creating analytics table in Supabase...")
    success = create_analytics_schema()
    
    if success:
        print("\n✅ Done! Now add the tracking script to docs/index.html")
    else:
        print("\n⚠️  Please run the SQL manually in Supabase dashboard")
